import { ChangeEvent, ReactElement, useEffect, useState } from 'react'
import Tooltip from '@shared/atoms/Tooltip'
import Input from '@shared/FormInput'
import FormHelp from '@shared/FormInput/Help'
import IconUrl from '@images/url.svg'
import IconS3Storage from '@images/s3_storage.svg'
import IconFtp from '@images/ftp.svg'
import { FormComputeData } from '../_types'
import { generateComputeOutputEncryptionKey } from '../outputStorage'
import styles from './index.module.css'

const outputStorageTabs = [
  { type: 'url', label: 'URL', icon: IconUrl },
  { type: 's3', label: 'S3', icon: IconS3Storage },
  { type: 'ftp', label: 'FTP/FTPS', icon: IconFtp }
] as const

type OutputStorageType = (typeof outputStorageTabs)[number]['type']

type SetFieldValue = (
  field: string,
  value: unknown,
  shouldValidate?: boolean
) => Promise<unknown>

type OutputStorageS3Access = NonNullable<
  NonNullable<FormComputeData['outputStorage']>['s3Access']
>

type S3StringFieldKey = Exclude<keyof OutputStorageS3Access, 'forcePathStyle'>

type StorageFieldConfig<K extends string = string> = {
  key: K
  label: string
  help?: string
  placeholder: string
  type?: 'text' | 'url' | 'password'
}

const s3FieldConfigs: StorageFieldConfig<S3StringFieldKey>[] = [
  {
    key: 'endpoint',
    label: 'Endpoint URL',
    help: 'S3 endpoint URL (e.g., https://s3.amazonaws.com for AWS S3, or your custom S3-compatible endpoint)',
    placeholder:
      'e.g. https://s3.amazonaws.com or https://nyc3.digitaloceanspaces.com'
  },
  {
    key: 'region',
    label: 'Region',
    help: 'Region (e.g., us-east-1). Optional; defaults to us-east-1 if omitted. Ensure the input value contains no spaces, as some S3 providers cannot process them.',
    placeholder: 'e.g. us-east-1 (optional)'
  },
  {
    key: 'bucket',
    label: 'Bucket Name',
    help: 'S3 bucket name where the file is stored. Ensure the input value contains no spaces, as some S3 providers cannot process them.',
    placeholder: 'e.g. my-bucket'
  },
  {
    key: 'objectKey',
    label: 'Name',
    help: 'Folder and alias of the output file. (e.g. folder/alias-name). If you input only the folder, the file name will be generated by the node.',
    placeholder: 'e.g. folder/alias-name'
  },
  {
    key: 'accessKeyId',
    label: 'Access Key ID',
    help: 'Access key for the S3-compatible API',
    placeholder: 'e.g. AKIAIOSFODNN7EXAMPLE'
  },
  {
    key: 'secretAccessKey',
    label: 'Secret Access Key',
    help: 'Secret key for the S3-compatible API',
    placeholder: 'e.g. wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
    type: 'password'
  }
]

function StorageTypeTab({
  isActive,
  label,
  icon: Icon,
  onClick
}: {
  isActive: boolean
  label: string
  icon: typeof IconUrl
  onClick: () => void
}): ReactElement {
  return (
    <button
      type="button"
      className={`${styles.outputStorageTab} ${
        isActive ? styles.outputStorageTabActive : ''
      }`}
      onClick={onClick}
    >
      <Icon className={styles.outputStorageTabIcon} />
      <span>{label}</span>
    </button>
  )
}

function StorageCheckbox({
  checked,
  label,
  help,
  onChange
}: {
  checked: boolean
  label: string
  help?: string
  onChange: (checked: boolean) => void
}): ReactElement {
  return (
    <label className={styles.outputCheckboxLabel}>
      <input
        type="checkbox"
        checked={checked}
        onChange={(e) => onChange(e.target.checked)}
        className={styles.outputCheckbox}
      />
      <span className={styles.outputCheckboxText}>
        {label}
        {help && (
          <Tooltip
            placement="top"
            content={<div className={styles.outputTooltipContent}>{help}</div>}
          />
        )}
      </span>
    </label>
  )
}

function StorageInputField({
  name,
  label,
  help,
  placeholder,
  type = 'text',
  value,
  onChange
}: Omit<StorageFieldConfig, 'key'> & {
  name: string
  value: string
  onChange: (event: ChangeEvent<HTMLInputElement>) => void
}): ReactElement {
  return (
    <Input
      name={name}
      label={label}
      help={help}
      type={type}
      value={value}
      onChange={onChange}
      placeholder={placeholder}
    />
  )
}

export default function OutputStorageSection({
  values,
  setFieldValue
}: {
  values: FormComputeData
  setFieldValue: SetFieldValue
}): ReactElement {
  const storageType = (values.outputStorage?.type || 'url') as OutputStorageType
  const [copyFeedback, setCopyFeedback] = useState<'idle' | 'copied' | 'error'>(
    'idle'
  )

  useEffect(() => {
    if (copyFeedback === 'idle') return

    const timeout = window.setTimeout(() => {
      setCopyFeedback('idle')
    }, 2500)

    return () => window.clearTimeout(timeout)
  }, [copyFeedback])

  const updateOutputStorage = (field: string, value: string | boolean) => {
    setFieldValue(`outputStorage.${field}`, value)
  }

  const updateS3Storage = (field: string, value: string | boolean) => {
    setFieldValue(`outputStorage.s3Access.${field}`, value)
  }

  const getS3FieldValue = (field: S3StringFieldKey): string => {
    return values.outputStorage?.s3Access?.[field] || ''
  }

  const handleEncryptionToggle = (checked: boolean) => {
    setFieldValue('outputStorage.useEncryption', checked)
    if (!checked) setCopyFeedback('idle')
  }

  const handleEncryptionKeyChange = (value: string) => {
    const sanitizedValue = value
      .replace(/[^0-9a-f]/gi, '')
      .slice(0, 64)
      .toLowerCase()

    updateOutputStorage('encryptionKey', sanitizedValue)
    if (copyFeedback !== 'idle') {
      setCopyFeedback('idle')
    }
  }

  const handleCopyEncryptionKey = async () => {
    const encryptionKey = values.outputStorage?.encryptionKey?.trim()
    if (!encryptionKey) return

    try {
      await navigator.clipboard.writeText(encryptionKey)
      setCopyFeedback('copied')
    } catch {
      setCopyFeedback('error')
    }
  }

  return (
    <div className={styles.outputStorageSection}>
      <div className={styles.outputStorageCard}>
        <div className={styles.outputStorageTabs}>
          {outputStorageTabs.map((tab) => (
            <StorageTypeTab
              key={tab.type}
              isActive={storageType === tab.type}
              label={tab.label}
              icon={tab.icon}
              onClick={() => setFieldValue('outputStorage.type', tab.type)}
            />
          ))}
        </div>

        <div className={styles.outputStorageForm}>
          {storageType === 'url' && (
            <StorageInputField
              name="outputStorage.url"
              label="Destination URL"
              type="url"
              value={values.outputStorage?.url || ''}
              placeholder="https://storage.example.com/results/"
              onChange={(e) => updateOutputStorage('url', e.target.value)}
            />
          )}

          {storageType === 's3' && (
            <div className={styles.outputGrid}>
              {s3FieldConfigs.map((fieldConfig) => (
                <StorageInputField
                  key={fieldConfig.key}
                  {...fieldConfig}
                  name={`outputStorage.s3Access.${fieldConfig.key}`}
                  value={getS3FieldValue(fieldConfig.key)}
                  onChange={(e) =>
                    updateS3Storage(fieldConfig.key, e.target.value)
                  }
                />
              ))}

              <div className={styles.outputGridFullWidth}>
                <StorageCheckbox
                  checked={Boolean(
                    values.outputStorage?.s3Access?.forcePathStyle
                  )}
                  label="Use path-style addressing"
                  help="If true, use path-style addressing (e.g., endpoint/bucket/key). Required for some S3-compatible services (e.g., MinIO). Default false (virtual-host style, standard for AWS S3)."
                  onChange={(checked) =>
                    updateS3Storage('forcePathStyle', checked)
                  }
                />
              </div>
            </div>
          )}

          {storageType === 'ftp' && (
            <StorageInputField
              name="outputStorage.url"
              label="FTP/FTPS URL"
              type="url"
              value={values.outputStorage?.url || ''}
              placeholder="ftps://user:password@host/path"
              onChange={(e) => updateOutputStorage('url', e.target.value)}
            />
          )}

          <StorageCheckbox
            checked={Boolean(values.outputStorage?.useEncryption)}
            label="Encrypt the exported job results"
            help="Encrypt the exported job results before they are written to your remote destination."
            onChange={handleEncryptionToggle}
          />

          {values.outputStorage?.useEncryption && (
            <div className={styles.encryptionKeySection}>
              <StorageInputField
                name="outputStorage.encryptionKey"
                label="Encryption Key"
                value={values.outputStorage?.encryptionKey || ''}
                placeholder="64 hex characters"
                onChange={(e) => handleEncryptionKeyChange(e.target.value)}
              />

              <div className={styles.encryptionKeyActions}>
                <button
                  type="button"
                  className={styles.encryptionActionButton}
                  onClick={() =>
                    updateOutputStorage(
                      'encryptionKey',
                      generateComputeOutputEncryptionKey()
                    )
                  }
                >
                  Generate
                </button>
                <button
                  type="button"
                  className={styles.encryptionActionButton}
                  onClick={handleCopyEncryptionKey}
                  disabled={!values.outputStorage?.encryptionKey?.trim()}
                >
                  Copy
                </button>
                {copyFeedback === 'copied' && (
                  <span className={styles.encryptionStatus}>Copied.</span>
                )}
                {copyFeedback === 'error' && (
                  <span className={styles.encryptionStatusError}>
                    Copy failed. Copy it manually.
                  </span>
                )}
              </div>

              <FormHelp className={styles.encryptionKeyHint}>
                Provide a 32-byte key encoded as 64 hexadecimal characters.
              </FormHelp>
              <FormHelp className={styles.encryptionKeyHint}>
                Copy this key and store it safely. You will need the same
                32-byte key to decrypt the exported result later.
              </FormHelp>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
